stages:
  - login

login-to-ec2:
  image: ubuntu:latest
  stage: login
 
  script:
    - sudo apt update
    - ssh -i "$LOGIN_FILE" $USER@$PASSWD 
    - echo "login successful"

    - echo "into server"
    - exit
