stages:
  - login

login-to-ec2:
  image: ubuntu:latest
  stage: login
  before_script:
    - ssh -i "$LOGIN_FILE" $USER@$PASSWD 
    - echo "login successful"

  script:
    - echo "into server"
    - exit
    